modLoader="javafml" 
loaderVersion="${loader_version_range}" 
license="${mod_license}"
[[mods]] 
modId="dynamictrees_createcompat" 
version="${mod_version}" 
displayName="${mod_name}" 
authors="${mod_authors}" 

description='''${mod_description}'''
[[dependencies.dynamictrees_createcompat]]
   modId="forge" 
   mandatory=true 
   versionRange="${forge_version_range}" 
   ordering="NONE"
   side="BOTH"
[[dependencies.dynamictrees_createcompat]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
